// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6llx_1QQpc2ZbKKenqONRDQ5TXfO2nXs',
    appId: '1:163578232522:web:5827dfeee0ce2f954c3e33',
    messagingSenderId: '163578232522',
    projectId: 'bizconnect-f788a',
    authDomain: 'bizconnect-f788a.firebaseapp.com',
    storageBucket: 'bizconnect-f788a.appspot.com',
    measurementId: 'G-W9LY7F88W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPoXqU9KSXyEHClJhLehDHmR4Ud-6GOo',
    appId: '1:163578232522:android:79270a893b7090624c3e33',
    messagingSenderId: '163578232522',
    projectId: 'bizconnect-f788a',
    storageBucket: 'bizconnect-f788a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4j1piGfvohkITmfzXTxr51yzDxqu3Wzo',
    appId: '1:163578232522:ios:1b6ee79cb4e025c84c3e33',
    messagingSenderId: '163578232522',
    projectId: 'bizconnect-f788a',
    storageBucket: 'bizconnect-f788a.appspot.com',
    androidClientId: '163578232522-2t79luslfhhnlq47hnordkb65k8ir26g.apps.googleusercontent.com',
    iosClientId: '163578232522-5jm4hith2pr8nv0ebuqkc0jv65l4hgtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalAppCu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4j1piGfvohkITmfzXTxr51yzDxqu3Wzo',
    appId: '1:163578232522:ios:1b6ee79cb4e025c84c3e33',
    messagingSenderId: '163578232522',
    projectId: 'bizconnect-f788a',
    storageBucket: 'bizconnect-f788a.appspot.com',
    androidClientId: '163578232522-2t79luslfhhnlq47hnordkb65k8ir26g.apps.googleusercontent.com',
    iosClientId: '163578232522-5jm4hith2pr8nv0ebuqkc0jv65l4hgtp.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalAppCu',
  );
}
